# Generated by Django 5.0.4 on 2024-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.ImageField(upload_to='movie_images/')),
                ('duration', models.IntegerField()),
                ('genre', models.JSONField()),
                ('language', models.CharField(max_length=50)),
                ('mpaaRatingType', models.CharField(max_length=50)),
                ('mpaaRatingLabel', models.CharField(max_length=100)),
                ('userRating', models.FloatField()),
            ],
        ),
    ]
